/* tslint:disable */
/* eslint-disable */

/* auto-generated by NAPI-RS */

export declare function hammingDistance(hash1: string, hash2: string): number
export declare function batchHash(imagePaths: Array<string>, algorithm: string): Array<string>
export declare function xxhash64(data: Buffer): string
export interface ImageInfo {
  width: number
  height: number
  format: string
  hasAlpha: boolean
}
export declare function getImageInfo(imagePath: string): ImageInfo
export declare class ImageHasher {
  constructor()
  ahash(imagePath: string): string
  dhash(imagePath: string): string
  phash(imagePath: string): string
}
